name: CI Pipeline & Docker Build

# Trigger: Jalan setiap kali ada Push
on: [push]

env:
  # Variable global untuk DagsHub
  DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Ambil kode dari repo
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Siapkan Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    # 3. Install Library
    - name: Install Dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn seaborn matplotlib mlserver mlserver-mlflow

    # 4. Login ke Docker Hub (Agar bisa upload)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 5. Jalankan Training (File MLProject)
    - name: Run MLProject (Training)
      working-directory: ./MLProject
      run: |
        # Jalankan training. Script python akan otomatis membuat file run_id.txt
        mlflow run . --env-manager=local

    # 6. Build Docker Image & Push (BAGIAN ADVANCE)
    - name: Build and Push Docker Image
      working-directory: ./MLProject
      run: |
        # Baca Run ID dari file txt yang dibuat oleh modelling.py tadi
        if [ -f run_id.txt ]; then
            RUN_ID=$(cat run_id.txt)
            echo "Detected Run ID: $RUN_ID"
        else
            echo " Error: run_id.txt not found!"
            exit 1
        fi
        
        # Tentukan Nama Image: username/nama-image:tag
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/msml:latest"
        
        # Perintah MLflow untuk bungkus model jadi Docker
        echo "Building Docker Image..."
        # Mengambil model bernama 'model_final' sesuai script python
        mlflow models build-docker -m "runs:/$RUN_ID/model_final" -n "$IMAGE_NAME" --enable-mlserver
        
        # Upload ke Docker Hub
        echo "Pushing to Docker Hub..."
        docker push "$IMAGE_NAME"
