name: CI Pipeline & Docker Build

# Trigger: Jalan setiap kali ada Push
on: [push]

# Variabel Global (Akan tersedia di semua steps)
env:
  DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  MLFLOW_TRACKING_URI: "https://dagshub.com/Tikleboy/Eksperimen_SML_StanlyLopez.mlflow"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Ambil kode dari repo
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Siapkan Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install Library
    - name: Install Dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn seaborn matplotlib mlserver mlserver-mlflow

    # 4. Login ke Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 5. Jalankan Training (File MLProject)
    - name: Run MLProject (Training)
      working-directory: ./MLProject
      # PENTING: Environment variable diwariskan ke perintah ini
      run: |
        mlflow run . --env-manager=local
      env:
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}

    # 6. Build Docker Image & Push
    - name: Build and Push Docker Image
      working-directory: ./MLProject
      run: |
        echo "Mencari Run ID terbaru dari DagsHub..."
        
        # Script inline python untuk mencari ID terakhir
        RUN_ID=$(python -c "import mlflow; mlflow.set_tracking_uri('${{ env.MLFLOW_TRACKING_URI }}'); runs = mlflow.search_runs(experiment_names=['CI_Pipeline_Experiment'], order_by=['start_time DESC'], max_results=1); print(runs.iloc[0].run_id)")
        
        if [ -z "$RUN_ID" ]; then
          echo "Error: Tidak ditemukan Run ID!"
          exit 1
        fi
        
        echo "Detected Run ID: $RUN_ID"
        
        # Tentukan Nama Image
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/sml:latest"
        
        echo "ðŸ”¨ Building Docker Image..."
        # Kita set env vars lagi agar perintah build-docker punya akses
        export MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_USERNAME }}
        export MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}
        export MLFLOW_TRACKING_URI=${{ env.MLFLOW_TRACKING_URI }}
        
        mlflow models build-docker -m "runs:/$RUN_ID/model_final" -n "$IMAGE_NAME" --enable-mlserver
        
        echo "Pushing to Docker Hub..."
        docker push "$IMAGE_NAME"
